#### Dataframes

#### Dataframes
- Are a table-like data structure with rows, columns and labels, commonly used to organize and analyze data in Python.

#### Series
- Is one column of the dataframe with its label

In [4]:
import pandas as pd

df = pd.DataFrame({
    "month": ["Jan", "Feb", "Mar", "Apr", "May", "Jun"],
    "channel":["web", "web", "partner", "web", "partner", "web"],
    "signups":[42, 48, 51, 57, 61, 66],
    "campaign":["winter", "winter", "referral", "spring", "referral", "spring"]
})

df

  month  channel  signups  campaign
0   Jan      web       42    winter
1   Feb      web       48    winter
2   Mar  partner       51  referral
3   Apr      web       57    spring
4   May  partner       61  referral
5   Jun      web       66    spring

#### Inspection
The first habit to develop is to inspect the dataframes before starting any work.
- number of rows and columns
- labels
- types of the series

In [10]:
print(df.head())
print(f"\nThe dataframe has {df.shape[0]} rows and {df.shape[1]} columns")
print(f"\nThe columns are: {df.columns}") # column labels
print(f"\nThe data types are: {df.dtypes}") # columns data types

  month  channel  signups  campaign
0   Jan      web       42    winter
1   Feb      web       48    winter
2   Mar  partner       51  referral
3   Apr      web       57    spring
4   May  partner       61  referral

The dataframe has 6 rows and 4 columns

The columns are: Index(['month', 'channel', 'signups', 'campaign'], dtype='str')

The data types are: month         str
channel       str
signups     int64
campaign      str
dtype: object

#### Selecting of columns

In [12]:
signups = df["signups"] # one column -> single brackets
print(signups)

monthly_signups = df[["month", "signups"]] # list of columns -> smaller table
print(monthly_signups)

0    42
1    48
2    51
3    57
4    61
5    66
Name: signups, dtype: int64
  month  signups
0   Jan       42
1   Feb       48
2   Mar       51
3   Apr       57
4   May       61
5   Jun       66

#### Row filtering

In [16]:
# Boolean mask: True for rows where signups >= 55
df["signups"] >= 55

0    False
1    False
2    False
3     True
4     True
5     True
Name: signups, dtype: bool

In [17]:
# keep only rows where signups >= 55
df[df["signups"] >= 55]

  month  channel  signups  campaign
3   Apr      web       57    spring
4   May  partner       61  referral
5   Jun      web       66    spring

#### Summaries

- `.describe()` give a compact first pass over the data

In [22]:
print(f"The mean of signups is {df['signups'].mean()}")
print(f'\ncount of channels: {df["channel"].value_counts()}')
print(f'\nGeneral description of the dataframe: \n{df.describe(include="all")}')

The mean of signups is 54.166666666666664

count of channels: channel
web        4
partner    2
Name: count, dtype: int64

General description of the dataframe:
       month channel    signups campaign
count      6       6   6.000000        6
unique     6       2        NaN        3
top      Jan     web        NaN   winter
freq       1       4        NaN        2
mean     NaN     NaN  54.166667      NaN
std      NaN     NaN   8.841191      NaN
min      NaN     NaN  42.000000      NaN
25%      NaN     NaN  48.750000      NaN
50%      NaN     NaN  54.000000      NaN
75%      NaN     NaN  60.000000      NaN
max      NaN     NaN  66.000000      NaN

#### Sorting

In [23]:
df.sort_values(by="signups", ascending=False)

  month  channel  signups  campaign
5   Jun      web       66    spring
4   May  partner       61  referral
3   Apr      web       57    spring
2   Mar  partner       51  referral
1   Feb      web       48    winter
0   Jan      web       42    winter

#### Example:

- inspect the table,
- choose a column of interest,
- apply a rule,
- inspect the subset,
- summarize what seems worth pursuing next.

In [29]:
subset = df[df["signups"] >= 50]

print(subset[["month", "campaign", "signups"]])
print(f'--' * 30)
print(subset["campaign"].value_counts())

  month  campaign  signups
2   Mar  referral       51
3   Apr    spring       57
4   May  referral       61
5   Jun    spring       66
------------------------------------------------------------
campaign
referral    2
spring      2
Name: count, dtype: int64