In [1]:
import sys
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path.cwd()
if not (PROJECT_ROOT / "src").exists():
    PROJECT_ROOT = PROJECT_ROOT.parent
sys.path.insert(0, str(PROJECT_ROOT))

from src.core import load_data, clean_trips, trips_by_city, save_clean_trips

data_path = PROJECT_ROOT / "data" / "trips_raw.csv"
trips = load_data(data_path)

trips.head()

     city        date days_spent  budget_eur                     notes
0  Berlin  2026-03-27          3       450.0  conference, late arrival
1   Paris  2026-03-30                  600.0       weekend, metro card
2  berlin  2026∕04∕10          2       310.5           friends, museum
3  Lisbon  2026-04-15          5         NaN                 surf trip
4   Paris  2026-03-30          3       600.0       weekend, metro card

In [2]:
trips.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   city        5 non-null      str
 1   date        5 non-null      str
 2   days_spent  5 non-null      str
 3   budget_eur  4 non-null      float64
 4   notes       5 non-null      str
dtypes: float64(1), str(4)
memory usage: 332.0 bytes

In [3]:
trips.isna().sum()

city          0
date          0
days_spent    0
budget_eur    1
notes         0
dtype: int64

In [4]:
cities = trips_by_city(trips)
print(cities)

city
Paris     2
Berlin    1
berlin    1
Lisbon    1
Name: count, dtype: int64

### Data Cleaning Steps

These cleaning steps ensure consistent and reliable analysis.  
We use pandas string, datetime, and numeric conversion methods to standardize column formats (e.g., city names, dates, and numeric values), handle missing or invalid data (`errors="coerce"` replaces wrong values with NaN), and remove duplicate rows with `drop_duplicates()`. This improves data quality and prevents errors in downstream analysis.

In [5]:
trips = clean_trips(trips)
trips.head()

     city       date  days_spent  budget_eur                     notes
0  Berlin 2026-03-27         3.0       450.0  conference, late arrival
1   Paris 2026-03-30         NaN       600.0       weekend, metro card
2  Berlin        NaT         2.0       310.5           friends, museum
3  Lisbon 2026-04-15         5.0         NaN                 surf trip
4   Paris 2026-03-30         3.0       600.0       weekend, metro card

In [6]:
trips.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   city        5 non-null      str
 1   date        4 non-null      datetime64[us]
 2   days_spent  4 non-null      float64
 3   budget_eur  4 non-null      float64
 4   notes       5 non-null      str
dtypes: datetime64[us](1), float64(2), str(2)
memory usage: 332.0 bytes

In [7]:
trips.isna().sum()

city          0
date          1
days_spent    1
budget_eur    1
notes         0
dtype: int64

In [8]:
cities_clean = trips_by_city(trips)
print(cities_clean)

city
Berlin    2
Paris     2
Lisbon    1
Name: count, dtype: int64

In [9]:
clean_path = PROJECT_ROOT / "data" / "trips_cleaned.csv"
is_saved = save_clean_trips(trips, clean_path)

if is_saved:
    print(f"File svaed on {clean_path}")

File svaed on c:\Users\dacde\Documents\Curso ciencia de datos\Data_Science\3_Statistics_And_MachineLearning\labs\notebook_to_project\data\trips_cleaned.csv